name: Build

on: [push, workflow_dispatch]

jobs:
  build_desktop:
    name: Build Desktop on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install dependencies
      run: npm i
    - name: Build
      uses: samuelmeuli/action-electron-builder@v1.6.0
      with:
        github_token: ${{ secrets.github_token }}
        release: ${{ startsWith(github.ref, 'refs/tags/v') }}
        skip_build: true
##    - name: Get current version
##      uses: Saionaro/extract-package-version@v1.0.6
##      id: package-version
##    - name: Upload Artifact
##      uses: actions/upload-artifact@v2
##      if: matrix.os == 'macos-latest'
##      with:
##        name: 'spotify-controller-${{ steps.package-version.outputs.version }}'
##        path: 'release/spotify-controller-${{ steps.package-version.outputs.version }}.dmg'
